
const DEFAULT_INACTIVITY_TIME = 10000
const DEFAULT_SUBSCRIPTION_EXPIRY_TIME = 3.6e6

const MESSAGE_TYPES = {
    POSITION_UPDATE: "POSITION_UPDATE",
    QUERY: "QUERY",
    SUBSCRIBE: "SUBSCRIBE",
    UNSUBSCRIBE: "UNSUBSCRIBE"
}

module.exports = {
    DEFAULT_INACTIVITY_TIME,
    DEFAULT_SUBSCRIPTION_EXPIRY_TIME,
    MESSAGE_TYPES
}